# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Youtube_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxSwiftExt'
  pod 'RxDataSources'

  pod 'Swinject'

  pod 'IQKeyboardManagerSwift'

  pod 'SwifterSwift', '5.2.0'

  pod 'Kingfisher', '~> 7.0'

  pod 'SwiftLint'

  target 'Youtube_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Youtube_DemoUITests' do
    # Pods for testing
  end

end
